jwt:
  signing_key: 'qmPlus'
  expires_time: 604800
  buffer_time: 86400
  issuer: 'qmPlus'

mysql:
  path: 'localhost'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db_name: 'technical_blog'
  username: 'root'
  password: 'sm940706'
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: ''
  log_zap: false

zap:
  level: 'info'
  perfix: ''
  format: 'console'
  director: 'log'
  max_age: 30
  show_line: true
  log_in_console: true

system:
  env: 'public'
  addr: 4399
  use_redis: false
  oss_type: 'local'
  db_type: 'mysql'
